#!/bin/bash

echo "=== Vercel Project Information ==="
echo ""
echo "Чтобы получить VERCEL_ORG_ID и VERCEL_PROJECT_ID:"
echo ""
echo "1. Установите Vercel CLI:"
echo "   npm i -g vercel"
echo ""
echo "2. Войдите в аккаунт:"
echo "   vercel login"
echo ""
echo "3. В корне проекта выполните:"
echo "   vercel"
echo ""
echo "4. После деплоя в проекте появится файл .vercel/project.json"
echo "   Из него можно получить нужные ID"
echo ""
echo "Или получите ID из Vercel Dashboard:"
echo "- ORG_ID: Settings → General → Team ID"  
echo "- PROJECT_ID: Project → Settings → General → Project ID"