#!/bin/bash

echo "🎯 GitHub Secrets Setup для myometrics-frontend"
echo ""
echo "Перейдите в:"
echo "https://github.com/mMedcon/myometrics-frontend/settings/secrets/actions"
echo ""
echo "Добавьте эти секреты:"
echo ""
echo "1️⃣ VERCEL_TOKEN"
echo "   Value: [ваш длинный API токен от Vercel]"
echo ""
echo "2️⃣ VERCEL_ORG_ID" 
echo "   Value: team_pz4u8iKxtEnn9R8M9bQ9vNGR"
echo ""
echo "3️⃣ VERCEL_PROJECT_ID"
echo "   Value: prj_5CqUVqBy609k1fTqGfJDVLadM3Me"
echo ""
echo "После добавления всех секретов - сделайте push в main ветку"
echo "и деплой должен работать! 🚀"